CREATE TABLE HTTP_SESSION
(
    PRIMARY_ID            CHAR(36) NOT NULL,
    SESSION_ID            CHAR(36) NOT NULL,
    CREATION_TIME         BIGINT   NOT NULL,
    LAST_ACCESS_TIME      BIGINT   NOT NULL,
    MAX_INACTIVE_INTERVAL INT      NOT NULL,
    EXPIRY_TIME           BIGINT   NOT NULL,
    PRINCIPAL_NAME        VARCHAR(100),
    CONSTRAINT HTTP_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX HTTP_SESSION_IX1 ON HTTP_SESSION (SESSION_ID);
CREATE INDEX HTTP_SESSION_IX2 ON HTTP_SESSION (EXPIRY_TIME);
CREATE INDEX HTTP_SESSION_IX3 ON HTTP_SESSION (PRINCIPAL_NAME);

CREATE TABLE HTTP_SESSION_ATTRIBUTES
(
    SESSION_PRIMARY_ID CHAR(36)      NOT NULL,
    ATTRIBUTE_NAME     VARCHAR(200)  NOT NULL,
    ATTRIBUTE_BYTES    LONGVARBINARY NOT NULL,
    CONSTRAINT HTTP_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT HTTP_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES HTTP_SESSION (PRIMARY_ID) ON DELETE CASCADE
);